### ISSUE TITLE
Pull requests here won’t count toward Hacktoberfest.

### ISSUE THREAD

**Issue by hacktoberfest-team** [wajahatkarim3/Hacktoberfest2019#25]
Hi there,

Thanks for your interest in Hacktoberfest and helping others learn how to make their first contributions to open source!

That said, high-quality contributions are part of the [the core values of Hacktoberfest](https://hacktoberfest.digitalocean.com/details), so we kindly ask that you do not create repositories which allow users to quickly gain a PR toward completing the challenge.

We encourage you to take a look at our list of [Hacktoberfest issues](https://hacktoberfest.digitalocean.com/#projects) for inspiration and ideas about making meaningful contributions to open source projects.

_Due to this, we've added this repository to our list of excluded repositories and pull requests here will not count toward Hacktoberfest 2019. Please note, you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest._

Happy Hacking,
The Hacktoberfest Team

Hacktoberfest is presented by [DigitalOcean](https://do.co/hacktoberfest50) and [DEV](https://dev.to).

**Comment by wajahatkarim3** [comment]
Thank you @hacktoberfest-team for letting me know. This repository is created to teach the beginners on how to create the Pull Request and how to contribute on Github in this article. https://android.jlelse.eu/the-beginners-guide-to-hacktoberfest-2019-winning-the-t-shirt-1a03b67e68

**Comment by hacktoberfest-team** [comment]
@wajahatkarim3 you are welcome to keep running this repository as a learning tool for new contributors to open-source, but pull requests won’t count toward Hacktoberfest as they do not align with the core values of Hacktoberfest. If you have any more questions, you are welcome to contact hacktoberfest@digitalocean.com

**Comment by wajahatkarim3** [comment]
Yeah. I totally get that. Also, I have added a disclaimer in the Read Me page of this repository to notify users that pull requests won't count to hacktoberfest. 
Thank you for such an amazing festival and cooperation. 👍
