### ISSUE TITLE
hacktoberfest2019

### ISSUE THREAD

**Issue by nersus15** [wajahatkarim3/Hacktoberfest2019#818]

**Comment by czy5074** [comment]
They will count them if you PR get merge in. Maybe I am wrong.

**Comment by nersus15** [comment]
oooh ok thank you, they count them

**Comment by czy5074** [comment]
Let’s work together to reduce spam
● Spammy PRs can be labeled as “invalid.” Maintainers are faced with the majority of spam that occurs during Hacktoberfest, and we dislike spam just as much as you. If you’re a maintainer, please label any spammy PRs submitted to the repositories you maintain as invalid, and close them. PRs with this label won't count toward Hacktoberfest.

● There’s a seven-day review window for PRs. This year, we've implemented a new seven-day grace period that all PRs for Hacktoberfest must go through before they count toward completing the challenge. Once a participant has submitted four eligible PRs (ready-to-review, not drafts), the review window begins. This period gives maintainers time to identify and label spammy PRs as invalid. If the PRs are not marked invalid within that window, they will allow the user to complete the Hacktoberfest challenge. If any of the PRs are labeled as invalid, however, the user will return to the pending state until they have four eligible PRs, at which point the review period will then start again.

● Bad repositories will be excluded. In the past, we've seen many repositories that encourage participants to make simple PRs – such as adding their name to a file – to quickly gain a PR toward winning Hacktoberfest. While this may be a learning tool for new contributors, it goes against one of our core values for Hacktoberfest. The quality of pull requests is paramount; quantity comes second. These repositories do not encourage quality contributions and provide an unfair advantage in completing the Hacktoberfest challenge. This year, we've implemented a system to block these repositories, and any pull requests submitted to such repositories will not be counted. If you’d like to report a repository, please fill out the form linked below.

**Comment by czy5074** [comment]
https://hacktoberfest.digitalocean.com/details

You can check here for more detail.

This repo may be `Bad repository`.

**Comment by czy5074** [comment]
You can also use this link to check your status.
https://hacktoberfest.digitalocean.com/profile
![image](https://user-images.githubusercontent.com/27984559/67484241-a432c100-f635-11e9-8ccc-e64ce00d4fdd.png)
